# Investigation of NOAA's wind data
[The National Oceanic and Atmospheric Administration](https://www.noaa.gov) maintains a series of weather stations called [Automated Surface Observation Systems](http://www.hurricanescience.org/science/observation/landbased/automatedsurfaceobssystems/) (ASOS). They offer one-minute and five-minute interval data at these FTP sites:
* ftp://ftp.ncdc.noaa.gov/pub/data/asos-onemin/  
* ftp://ftp.ncdc.noaa.gov/pub/data/asos-fivemin/  

The structure of the five-minute interval data is [explained in this pdf](ftp://ftp.ncdc.noaa.gov/pub/data/documentlibrary/tddoc/td6401b.pdf) from NOAA.

### Libraries and installs

In [14]:
import pandas as pd
import pandas_profiling
import numpy as np 
import json
import os
import datetime
import re
from fastparquet import write
from matplotlib import pyplot as plt 
import gmplot

import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', 500)

### Data Folder Instructions

In [5]:
# Use this cell to specify the paths for the data folder in your local machines
# Use the variable 'datafolder' to specify the path
# Comment out all the data paths except your own
# NOAA data ia assumed to be in a subfolder called 'noaa' 
# For example, if the base data folder is '/users/data', noaa data should be in '/users/data/noaa'

# Angshuman's local path
datafolder = "/Users/apaul2/Documents/_Common/capstone/Project/data"

The ASOS data for current month was downloaded from ftp://ftp.ncdc.noaa.gov/pub/download/hidden/onemin/ and stored locally. The next few cells read all the data files for the current month and filter out the data for a single day for analysis.

In [19]:
dirpath = "{}/noaa/fmd_201909".format(datafolder)
entries = os.listdir(dirpath)
lines = [] # an array of each read line
for entry in entries:
    filepath = os.path.join(dirpath, entry)
    try:
        for line in pd.read_csv(filepath_or_buffer=filepath , encoding='utf-8', header=None, chunksize=1):
            lines.append(line.iloc[0,0])
    except:
        pass

In [21]:
print("ASOS data for September has ",len(lines)," records as of 3 PM 09/29")

ASOS data for September has  6168774  records as of 3 PM 09/29

In [26]:
def createNOAAdf(lines, fileName):
    """ Helper function to process noaa data"""
    
    # split lines and data chunks
    data = [] # an array of arrays, inner arrays are all data for one record, outer array is all records
    for line in lines:

        # reset any variables if needed
        record = [] 
        Report_Modifier = ''
        Wind_Data = False 
        Variable_Winds = False
        Gusts = False
        Wind_Direction = ''
        Wind_Speed = ''
        Gust_Speed = ''
        Variable_Wind_Info = ''
        System_Maintenance_Reqd = False

        line = line.split() # take string of one record's data and split into space separated chunks
        WBAN_Number = line[0][0:5] # The WBAN (Weather Bureau, Army, Navy) number is a unique 5-digit number
        Call_Sign = line[0][5:] # The call sign is a location identifier, three or four characters in length 
        suffix = line[1][-2:] # grab the last two digits that are the year (i.e. 19 for 2019)
        Year = '20'+suffix # in YYYY format
        CallSign_Date = re.split(Year, line[1])
        Call_Sign2 = CallSign_Date[0] # this seems to be the same as Call_Sign but without initial letter
        Date = CallSign_Date[1]
        Month = Date[0:2] # in MM format
        Day = Date[2:4] # in DD format
        Hour = Date[4:6] # in HH format
        Minute = Date[6:8] # Observations are recorded on whole five-minute increments (i.e. 00,05,10,...,50,55)
        Record_Length = Date[8:11] # I'm not sure what this is yet - Length of record??
        Date = Date[11:] # MM/DD/YY format
        Timestamp = line[2] # in HH:MM:SS format
        Interval = line[3] # should be 5-MIN as opposed to 1-MIN
        Call_Sign3 = line[4] # for some reason, a THIRD output of the call sign. random.
        Zulu_Time = line[5] # Zulu Time, or military time, or UTC

        # after this point, data could be missing/optional and data positions are not fixed
        currIndx = 6
        try:
            Next_Data = line[currIndx]
            if not any(x in Next_Data for x in ['KT','SM']):
                Report_Modifier = Next_Data # AUTO for fully automated report, COR for correction to a previously disseminated report
                currIndx += 1
            Next_Data = line[currIndx]
            if "KT" in Next_Data:
                Wind_Data = True
                Wind_Direction = Next_Data[0:3] # in tens of degrees from true north
                if Next_Data[0:3] == 'VRB':
                    Variable_Winds = True
                Wind_Speed = Next_Data[3:5] # in whole knots (two digits)
                if Next_Data[5] == 'G':
                    Gusts = True
                    Gust_Speed = Next_Data[6:8] # speed in whole knots (two digits)
            else:
                Wind_Data = False
        except:
            print("OUT OF DATA AT FIELD {}".format(currIndx))
            print(line)
        finally:
            currIndx += 1

        try:
            Next_Data = line[currIndx]
            if Wind_Data:
                if (re.fullmatch(r'[0-9][0-9][0-9]V[0-9][0-9][0-9]', Next_Data)): #e.g. 180V240 = wind direction varies from 180 to 240 degrees
                    Variable_Wind_Info = Next_Data
                    Variable_Winds = True
        except:
            print("OUT OF DATA AT FIELD {}".format(currIndx))
            print(line)
            
        if line[-1] == '$':
            System_Maintenance_Reqd = True

        #Sea_Level_Pressure = line[13] # given in tenths of hectopascals (millibars). The last digits are recorded (125 means 1012.5)
        #Station_Type = line[18]
        Num_Fields = len(line)
        record = [WBAN_Number, Call_Sign, Call_Sign2, Year, Month, Day, Hour, Minute, Record_Length, Date, Timestamp, Interval, Call_Sign3, Zulu_Time, 
                  Report_Modifier, Wind_Data, Wind_Direction, Wind_Speed, Gusts, Gust_Speed, Variable_Winds, Variable_Wind_Info, System_Maintenance_Reqd, Num_Fields]
        col_names = ["wban_number", "call_sign", "call_sign2", "year", "month", "day", "hour", "minute", "rec_length", "date", "timestamp", "interval", "call_sign3", 
                     "zulu_time", "report_modifier", "wind_data", "wind_direction", "wind_speed", "gusts", "gust_speed", "variable_winds", "variable_wind_info", "sys_maint_reqd", "num_fields"]
        data.append(record)
    
    sample_df = pd.DataFrame(data, columns = col_names)
    
    # save Dataframe to file
    parquet_file = "{}/noaa/{}.parquet".format(datafolder, fileName)
    write(parquet_file, sample_df,compression='GZIP')
    
    return sample_df

In [27]:
noaa_df = createNOAAdf(lines, 'Sep2019')

OUT OF DATA AT FIELD 7
['93721KBWI', 'BWI20190914190004209/14/19', '19:00:31', '5-MIN', 'KBWI', '150000Z', '180']
OUT OF DATA AT FIELD 8
['93721KBWI', 'BWI20190914190004209/14/19', '19:00:31', '5-MIN', 'KBWI', '150000Z', '180']
OUT OF DATA AT FIELD 8
['24029KSHR', 'SHR20190911223504409/11/19', '22:35:31', '5-MIN', 'KSHR', '120535Z', 'AUTO', '3']
OUT OF DATA AT FIELD 8
['13961KFTW', 'FTW20190925064004909/25/19', '06:40:32', '5-MIN', 'KFTW', '251240Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 7
['27406PASC', 'SCC20190914225005209/14/19', '22:50:31', '5-MIN', 'PASC', '150750Z', '08007KT0170000']
OUT OF DATA AT FIELD 8
['23191KAVX', 'AVX20190928085504909/28/19', '08:55:31', '5-MIN', 'KAVX', '281655Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 7
['12876KGIF', 'GIF20190924172504109/24/19', '17:25:31', '5-MIN', 'KGIF', '242225Z', 'AU1']
OUT OF DATA AT FIELD 8
['12876KGIF', 'GIF20190924172504109/24/19', '17:25:31', '5-MIN', 'KGIF', '242225Z', 'AU1']
OUT OF DATA AT FIELD 8
['12947KCOT', 'COT20190909043505309/09/19', '04:35:31', '5-MIN', 'KCOT', '091035Z', 'AUTO', '1302440233']
OUT OF DATA AT FIELD 7
['12935KPSX', 'PSX20190904024504809/04/19', '02:45:31', '5-MIN', 'KPSX', '040845Z', 'AU02610233']
OUT OF DATA AT FIELD 8
['12935KPSX', 'PSX20190904024504809/04/19', '02:45:31', '5-MIN', 'KPSX', '040845Z', 'AU02610233']
OUT OF DATA AT FIELD 8
['94023KGCC', 'GCC20190928124504909/28/19', '12:45:31', '5-MIN', 'KGCC', '281945Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 7
['03949KAQV', 'AQV20190904021004809/04/19', '02:10:31', '5-MIN', 'KAQV', '040810Z', 'AT02170200']
OUT OF DATA AT FIELD 8
['03949KAQV', 'AQV20190904021004809/04/19', '02:10:31', '5-MIN', 'KAQV', '040810Z', 'AT02170200']
OUT OF DATA AT FIELD 8
['14813KAKR', 'AKR20190926082004909/26/19', '08:20:31', '5-MIN', 'KAKR', '261320Z', 'AUTO', '30005K']
OUT OF DATA AT FIELD 7
['14737KABE', 'ABE20190916022004209/16/19', '02:20:31', '5-MIN', 'KABE', '160720Z', '000']
OUT OF DATA AT FIELD 8
['14737KABE', 'ABE20190916022004209/16/19', '02:20:31', '5-MIN', 'KABE', '160720Z', '000']
OUT OF DATA AT FIELD 7
['14737KABE', 'ABE20190925153004309/25/19', '15:30:31', '5-MIN', 'KABE', '252030Z', '2383']
OUT OF DATA AT FIELD 8
['14737KABE', 'ABE20190925153004309/25/19', '15:30:31', '5-MIN', 'KABE', '252030Z', '2383']
OUT OF DATA AT FIELD 8
['94765KLEB', 'LEB20190911014004909/11/19', '01:40:31', '5-MIN', 'KLEB', '110640Z', 'AUTO', '210071']
OUT OF DATA AT FIELD 8
['03928KICT', 'ICT20190908153004909/08/19', '15:30:31', '5-MIN', 'KICT', '082130Z', '15013G21K', '$']
OUT OF DATA AT FIELD 8
['03928KICT', 'ICT20190909032004209/09/19', '03:20:31', '5-MIN', 'KICT', '090920Z', '17', '$']
OUT OF DATA AT FIELD 7
['03928KICT', 'ICT20190911221504409/11/19', '22:15:31', '5-MIN', 'KICT', '120415Z', '670183']
OUT OF DATA AT FIELD 8
['03928KICT', 'ICT20190911221504409/11/19', '22:15:31', '5-MIN', 'KICT', '120415Z', '670183']
OUT OF DATA AT FIELD 8
['24219KDLS', 'DLS20190923112504909/23/19', '11:25:31', '5-MIN', 'KDLS', '231925Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 6
['03936KMHK', 'MHK20190918050536509/18/19', '05:05:31', '5-MIN', 'KMHK', '181105Z', 'AUKT', '10SM', 'FEW120', '23/19', 'A2993', '1050', '78', '2300', '000/00', 'RMK', 'AO2', 'T023301942400', '180/04', 'RMK', 'AO2', 'T024401941050', '73', '2400', '190/05', 'RMK', 'AO2', 'T0244019409/18/19', '05:20:31120Z', 'AUTO', '20004KT', '10SM', 'FEW120', '22400', '200/04', 'RMK', 'AO2', 'T024401941050', '76', '2400', '200/06', 'RMK', 'AO2', 'T0239019409/18/1993', 'TO', '20005KT', '10SM', 'CLR', '24/19', 'A2993', '2400', '200/05', 'RMK', 'AO2', 'SLP123', 'T0239', '58000']
OUT OF DATA AT FIELD 8
['93141KPUC', 'PUC20190906161504909/06/19', '16:15:31', '5-MIN', 'KPUC', '062315Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['94056KD07', 'D0720190908100004909/08/19', '10:00:31', '5-MIN', 'KD07', '081700Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['94056KD07', 'D0720190926171004909/26/19', '17:10:31', '5-MIN', 'KD07', '270010Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['93841KNSE', 'NSE20190910195504909/10/19', '19:55:31', '5-MIN', 'KNSE', '110155Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['63871K1J0', '1J020190905035504909/05/19', '03:55:31', '5-MIN', 'K1J0', '050955Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['63871K1J0', '1J020190908181504909/08/19', '18:15:31', '5-MIN', 'K1J0', '090015Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['63871K1J0', '1J020190919203004909/19/19', '20:30:31', '5-MIN', 'K1J0', '200230Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['63871K1J0', '1J020190920045004909/20/19', '04:50:31', '5-MIN', 'K1J0', '201050Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['63871K1J0', '1J020190922035004909/22/19', '03:50:32', '5-MIN', 'K1J0', '220950Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['63871K1J0', '1J020190922225004909/22/19', '22:50:31', '5-MIN', 'K1J0', '230450Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['63871K1J0', '1J020190923200004909/23/19', '20:00:32', '5-MIN', 'K1J0', '240200Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['63871K1J0', '1J020190925042504909/25/19', '04:25:31', '5-MIN', 'K1J0', '251025Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['63871K1J0', '1J020190926053004909/26/19', '05:30:31', '5-MIN', 'K1J0', '261130Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['63871K1J0', '1J020190926193004909/26/19', '19:30:32', '5-MIN', 'K1J0', '270130Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['63871K1J0', '1J020190926195004909/26/19', '19:50:31', '5-MIN', 'K1J0', '270150Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['63871K1J0', '1J020190927002004909/27/19', '00:20:31', '5-MIN', 'K1J0', '270620Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['63871K1J0', '1J020190927005004909/27/19', '00:50:32', '5-MIN', 'K1J0', '270650Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['63871K1J0', '1J020190927012504909/27/19', '01:25:31', '5-MIN', 'K1J0', '270725Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['63871K1J0', '1J020190927014504909/27/19', '01:45:31', '5-MIN', 'K1J0', '270745Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['63871K1J0', '1J020190927041004909/27/19', '04:10:31', '5-MIN', 'K1J0', '271010Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['63871K1J0', '1J020190927045504909/27/19', '04:55:32', '5-MIN', 'K1J0', '271055Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['63871K1J0', '1J020190927051004909/27/19', '05:10:31', '5-MIN', 'K1J0', '271110Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['63871K1J0', '1J020190927065504909/27/19', '06:55:32', '5-MIN', 'K1J0', '271255Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['63871K1J0', '1J020190927121504909/27/19', '12:15:32', '5-MIN', 'K1J0', '271815Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['63871K1J0', '1J020190927181504909/27/19', '18:15:32', '5-MIN', 'K1J0', '280015Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['63871K1J0', '1J020190927191504909/27/19', '19:15:31', '5-MIN', 'K1J0', '280115Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['63871K1J0', '1J020190927203004909/27/19', '20:30:31', '5-MIN', 'K1J0', '280230Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['63871K1J0', '1J020190927204004909/27/19', '20:40:31', '5-MIN', 'K1J0', '280240Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['63871K1J0', '1J020190927213504909/27/19', '21:35:31', '5-MIN', 'K1J0', '280335Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['63871K1J0', '1J020190928030004909/28/19', '03:00:31', '5-MIN', 'K1J0', '280900Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['63871K1J0', '1J020190928031004909/28/19', '03:10:31', '5-MIN', 'K1J0', '280910Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['23277KWVI', 'WVI20190907043504909/07/19', '04:35:32', '5-MIN', 'KWVI', '071235Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['03812KAVL', 'AVL20190905201504909/05/19', '20:15:31', '5-MIN', 'KAVL', '060115Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 7
['04836KFVE', 'FVE20190912230004309/12/19', '23:00:31', '5-MIN', 'KFVE', '130400Z', 'AUTO0']
OUT OF DATA AT FIELD 8
['04836KFVE', 'FVE20190912230004309/12/19', '23:00:31', '5-MIN', 'KFVE', '130400Z', 'AUTO0']
OUT OF DATA AT FIELD 8
['23007KCDS', 'CDS20190914152005109/14/19', '15:20:31', '5-MIN', 'KCDS', '142120Z', 'AUTO', '1701211']
OUT OF DATA AT FIELD 8
['23154KELY', 'ELY20190925011005309/25/19', '01:10:31', '5-MIN', 'KELY', '250910Z', 'AUTO2', 'T00830011']
OUT OF DATA AT FIELD 6
['92805KPMP', 'PMP20190924042545909/24/19', '04:25:31', '5-MIN', 'KPMP', '240925Z', 'AUKT', '10SM', 'CLR', '26/17', 'A2987', '70', '59', '1300', '040/04', 'RMK', 'AO2', 'T02560172', '$59', '1300', '030/04', 'RMK', 'AO2', 'T02560172', '$09/24/19', '04:35:3TO', '01003KT', '10SM', 'CLR', '26/17', 'A2987', '70', '59', '1300', '020/03', 'RMK', 'AO2', 'T02560172', '$63', '1200', '310/04', 'RMK', 'AO2', 'T02440172', '$66', '1200', '320/03', 'RMK', 'AO2', 'T02390172', '$68', '1200', '310/04', 'RMK', 'AO2', 'SLP117', 'T02390178', '$70', '1100', '310/04', 'RMK', 'AO2', 'T', '$70', '1100', '300/05', 'RMK', 'AO2', 'T02330178', '$75', '1000', '310/05', 'RMK', 'AO2', 'T', '$76', '1000', '330/05', 'RMK', 'AO2', 'T', '$MK', 'AO2', 'T02280183', '$']
OUT OF DATA AT FIELD 8
['24164KBPI', 'BPI20190911145504909/11/19', '14:55:31', '5-MIN', 'KBPI', '112155Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 7
['93784KDMH', 'DMH20190917084504209/17/19', '08:45:31', '5-MIN', 'KDMH', '171345Z', 'AUTO']
OUT OF DATA AT FIELD 8
['93784KDMH', 'DMH20190917084504209/17/19', '08:45:31', '5-MIN', 'KDMH', '171345Z', 'AUTO']
OUT OF DATA AT FIELD 8
['94012KHVR', 'HVR20190918215504909/18/19', '21:55:31', '5-MIN', 'KHVR', '190455Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['94178KTWF', 'TWF20190913074004909/13/19', '07:40:31', '5-MIN', 'KTWF', '131440Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['94178KTWF', 'TWF20190913074504909/13/19', '07:45:31', '5-MIN', 'KTWF', '131445Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['94178KTWF', 'TWF20190913075504909/13/19', '07:55:31', '5-MIN', 'KTWF', '131455Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 7
['53988KBKB', 'BKB20190903160504309/03/19', '16:05:31', '5-MIN', 'KBKB', '032205Z', 'AUTO']
OUT OF DATA AT FIELD 8
['53988KBKB', 'BKB20190903160504309/03/19', '16:05:31', '5-MIN', 'KBKB', '032205Z', 'AUTO']
OUT OF DATA AT FIELD 6
['53988KBKB', 'BKB20190906001004109/06/19', '00:10:31', '5-MIN', 'KBKB', '060610Z0211']
OUT OF DATA AT FIELD 7
['53988KBKB', 'BKB20190906001004109/06/19', '00:10:31', '5-MIN', 'KBKB', '060610Z0211']
OUT OF DATA AT FIELD 7
['53988KBKB', 'BKB20190909113004309/09/19', '11:30:31', '5-MIN', 'KBKB', '091730Z', '90233']
OUT OF DATA AT FIELD 8
['53988KBKB', 'BKB20190909113004309/09/19', '11:30:31', '5-MIN', 'KBKB', '091730Z', '90233']
OUT OF DATA AT FIELD 8
['53988KBKB', 'BKB20190910015504709/10/19', '01:55:31', '5-MIN', 'KBKB', '100755Z', 'AUTO', '0011']
OUT OF DATA AT FIELD 8
['53988KBKB', 'BKB20190913004005209/13/19', '00:40:31', '5-MIN', 'KBKB', '130640Z', 'AUTO', 'T02110200']
OUT OF DATA AT FIELD 8
['53988KBKB', 'BKB20190915030005309/15/19', '03:00:31', '5-MIN', 'KBKB', '150900ZMK', 'AO2', 'T02060189']
OUT OF DATA AT FIELD 7
['53988KBKB', 'BKB20190920174005009/20/19', '17:40:31', '5-MIN', 'KBKB', '202340Z', 'AUTT02500228']
OUT OF DATA AT FIELD 8
['53988KBKB', 'BKB20190920174005009/20/19', '17:40:31', '5-MIN', 'KBKB', '202340Z', 'AUTT02500228']
OUT OF DATA AT FIELD 7
['53988KBKB', 'BKB20190926132004009/26/19', '13:20:31', '5-MIN', 'KBKB', '261920Z', 'AU']
OUT OF DATA AT FIELD 8
['53988KBKB', 'BKB20190926132004009/26/19', '13:20:31', '5-MIN', 'KBKB', '261920Z', 'AU']
OUT OF DATA AT FIELD 8
['53988KBKB', 'BKB20190928091505209/28/19', '09:15:31', '5-MIN', 'KBKB', '281515Z', 'AUTO', 'VRB03KTNO']
OUT OF DATA AT FIELD 7
['03998KPPF', 'PPF20190924231510809/24/19', '23:15:31', '5-MIN', 'KPPF', '250515Z', 'AU81', 'KT', '10SM', 'OVC004', '21/21', 'A2982', '1000', '100', '2000', '200/06', 'RMK', 'AO2', 'T02110211']
OUT OF DATA AT FIELD 8
['03998KPPF', 'PPF20190925023005109/25/19', '02:30:31', '5-MIN', 'KPPF', '250830Z', 'AUTO', '2100878']
OUT OF DATA AT FIELD 8
['23293KSJC', 'SJC20190919142504909/19/19', '14:25:31', '5-MIN', 'KSJC', '192225Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 7
['92806KSPG', 'SPG20190918051504009/18/19', '05:15:31', '5-MIN', 'KSPG', '181015Z', 'AU']
OUT OF DATA AT FIELD 8
['92806KSPG', 'SPG20190918051504009/18/19', '05:15:31', '5-MIN', 'KSPG', '181015Z', 'AU']
OUT OF DATA AT FIELD 6
['94050KEEO', 'EEO20190913174017909/13/19', '17:40:31', '5-MIN', 'KEEO', '140040Z', 'AUKT', '10SM', 'CLR', '22/M', '6090', '23', '/03', 'RMK', 'AO2', 'T021', '18:00:30100Z', 'AUTO', '24003KT', '10SM', '6090', '23', '8300', '230/03', 'RMK', '700006090', '28', '/05', 'RMK', 'AO2', 'T0186090', '28', '30000']
OUT OF DATA AT FIELD 6
['94050KEEO', 'EEO20190913183516509/13/19', '18:35:31', '5-MIN', 'KEEO', '140135Z', 'AUKT', '10SM', 'CLR', '18/06090', '30', '7800', '310/06', 'RMK', 'AO2', 'T01709/13/19', '18:40:31', '5-MIN0140Z', 'AUTO', '310040', 'A3029', '6090', '30', '/04', 'RMK', 'AO2', 'T01780000']
OUT OF DATA AT FIELD 8
['24234KBFI', 'BFI20190921070004909/21/19', '07:00:32', '5-MIN', 'KBFI', '211500Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['24234KBFI', 'BFI20190921072004909/21/19', '07:20:31', '5-MIN', 'KBFI', '211520Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['24234KBFI', 'BFI20190921100504909/21/19', '10:05:31', '5-MIN', 'KBFI', '211805Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['24234KBFI', 'BFI20190921101004909/21/19', '10:10:31', '5-MIN', 'KBFI', '211810Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['24234KBFI', 'BFI20190921102504909/21/19', '10:25:31', '5-MIN', 'KBFI', '211825Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['24234KBFI', 'BFI20190921103004909/21/19', '10:30:31', '5-MIN', 'KBFI', '211830Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 8
['24234KBFI', 'BFI20190921111504909/21/19', '11:15:32', '5-MIN', 'KBFI', '211915Z', 'AUTO', 'RVRNO']
OUT OF DATA AT FIELD 6
['54757KELZ', 'ELZ20190908081511309/08/19', '08:15:31', '5-MIN', 'KELZ', '081315Z', 'AUKT', '7SM', 'F018', '13/12', 'A3010', '1960', '93', '2300', '050/04', 'RMK', 'AO2', 'CIG', '007V014', 'T01330122']

### Initial look at the data

In [28]:
noaa_df.head()

,wban_number,call_sign,call_sign2,year,month,day,hour,minute,rec_length,date,timestamp,interval,call_sign3,zulu_time,report_modifier,wind_data,wind_direction,wind_speed,gusts,gust_speed,variable_winds,variable_wind_info,sys_maint_reqd,num_fields
0,24154,KMLP,MLP,2019,09,01,00,00,135,09/01/19,00:00:31,5-MIN,KMLP,010800Z,AUTO,True,000,00,False,,False,,False,23
1,24154,KMLP,MLP,2019,09,01,00,05,136,09/01/19,00:05:31,5-MIN,KMLP,010805Z,AUTO,True,VRB,04,False,,True,,False,23
2,24154,KMLP,MLP,2019,09,01,00,10,136,09/01/19,00:10:31,5-MIN,KMLP,010810Z,AUTO,True,VRB,03,False,,True,,False,23
3,24154,KMLP,MLP,2019,09,01,00,15,138,09/01/19,00:15:31,5-MIN,KMLP,010815Z,AUTO,True,210,05,False,,False,,False,23
4,24154,KMLP,MLP,2019,09,01,00,20,138,09/01/19,00:20:31,5-MIN,KMLP,010820Z,AUTO,True,230,06,False,,False,,False,23

In [32]:
noaa_df[noaa_df.wind_speed == 'T']

,wban_number,call_sign,call_sign2,year,month,day,hour,minute,rec_length,date,timestamp,interval,call_sign3,zulu_time,report_modifier,wind_data,wind_direction,wind_speed,gusts,gust_speed,variable_winds,variable_wind_info,sys_maint_reqd,num_fields
2739677,03936,KMHK,MHK,2019,09,18,05,05,365,09/18/19,05:05:31,5-MIN,KMHK,181105Z,,True,AUK,T,False,,False,,False,57
4452667,92805,KPMP,PMP,2019,09,24,04,25,459,09/24/19,04:25:31,5-MIN,KPMP,240925Z,,True,AUK,T,False,,False,,True,85
5772065,94050,KEEO,EEO,2019,09,13,17,40,179,09/13/19,17:40:31,5-MIN,KEEO,140040Z,,True,AUK,T,False,,False,,False,33
5772077,94050,KEEO,EEO,2019,09,13,18,35,165,09/13/19,18:35:31,5-MIN,KEEO,140135Z,,True,AUK,T,False,,False,,False,27
6100357,54757,KELZ,ELZ,2019,09,08,08,15,113,09/08/19,08:15:31,5-MIN,KELZ,081315Z,,True,AUK,T,False,,False,,False,20

In [33]:
# Drop rows where wind speed is not numeric
noaa_df = noaa_df[noaa_df.wind_speed != 'T']

### Merge lat long data for stations

In [38]:
# Read from file that was stored earlier
station_df = pd.read_parquet("{}/noaa/station_data.parquet".format(datafolder))

In [39]:
station_df[station_df.wban_number == '21504']

,wban_number,descriptor,lat,lon,elev_m,begin_date,end_date
25041,21504,HILO INTERNATIONAL AIRPORT US HI PHTO,+19.719,-155.053,+0011.6,19730101,20190920
25042,21504,HILO GENERAL LYMAN ARPT US HI PHTO,+19.719,-155.053,+0011.0,19430415,19451228
28925,21504,HILO INTERNATIONAL AP US HI PHTO,+19.719,-155.053,+0011.0,19491001,19721231

In [40]:
# The station dataframe has multiple records for the same wban_number based on differing elevations and descriptors.
# Create a new dataframe with unique wban_number and lat-lon values to join with the ASOS data
unique_station_df = station_df.drop(['descriptor','elev_m','begin_date','end_date'], axis=1).drop_duplicates()

In [41]:
unique_station_df[unique_station_df.wban_number == '21504']

      wban_number      lat       lon
25041       21504  +19.719  -155.053

In [93]:
# Write to file
parquet_file = "{}/noaa/uniq_station_data.parquet".format(datafolder)
write(parquet_file, unique_station_df,compression='GZIP')

In [ ]:
# Read from file that was stored earlier
unique_station_df = pd.read_parquet("{}/noaa/uniq_station_data.parquet".format(datafolder))

In [42]:
merged_df = pd.merge(noaa_df, unique_station_df, on='wban_number')

In [43]:
merged_df.head()

,wban_number,call_sign,call_sign2,year,month,day,hour,minute,rec_length,date,timestamp,interval,call_sign3,zulu_time,report_modifier,wind_data,wind_direction,wind_speed,gusts,gust_speed,variable_winds,variable_wind_info,sys_maint_reqd,num_fields,lat,lon
0,24154,KMLP,MLP,2019,09,01,00,00,135,09/01/19,00:00:31,5-MIN,KMLP,010800Z,AUTO,True,000,0.0,False,NaN,False,,False,23,+47.457,-115.645
1,24154,KMLP,MLP,2019,09,01,00,05,136,09/01/19,00:05:31,5-MIN,KMLP,010805Z,AUTO,True,VRB,4.0,False,NaN,True,,False,23,+47.457,-115.645
2,24154,KMLP,MLP,2019,09,01,00,10,136,09/01/19,00:10:31,5-MIN,KMLP,010810Z,AUTO,True,VRB,3.0,False,NaN,True,,False,23,+47.457,-115.645
3,24154,KMLP,MLP,2019,09,01,00,15,138,09/01/19,00:15:31,5-MIN,KMLP,010815Z,AUTO,True,210,5.0,False,NaN,False,,False,23,+47.457,-115.645
4,24154,KMLP,MLP,2019,09,01,00,20,138,09/01/19,00:20:31,5-MIN,KMLP,010820Z,AUTO,True,230,6.0,False,NaN,False,,False,23,+47.457,-115.645

In [46]:
# Convert data type of numeric columns
merged_df[['wind_speed','gust_speed','lat','lon']] = merged_df[['wind_speed','gust_speed','lat','lon']].apply(pd.to_numeric)

In [47]:
merged_df.describe()

         wind_speed     gust_speed    num_fields           lat           lon
count  6.507357e+06  663690.000000  6.595372e+06  6.595372e+06  6.595372e+06
mean   5.960893e+00      21.424103  1.953388e+01  3.902964e+01 -9.614671e+01
std    4.534093e+00       4.859211  1.950849e+00  7.309837e+00  2.045387e+01
min    0.000000e+00      10.000000  6.000000e+00  1.348300e+01 -1.702220e+02
25%    3.000000e+00      18.000000  1.800000e+01  3.426200e+01 -1.085400e+02
50%    5.000000e+00      21.000000  1.900000e+01  3.929500e+01 -9.254300e+01
75%    9.000000e+00      24.000000  2.000000e+01  4.274600e+01 -8.168400e+01
max    5.100000e+01      71.000000  7.500000e+01  7.128300e+01  1.448000e+02

In [48]:
merged_df[["wban_number", "call_sign", "call_sign2", "year", "month", "day", "hour", "minute", "rec_length", "date", "timestamp",
"interval", "zulu_time", "report_modifier", "wind_data", "wind_direction", "gusts", "variable_winds", "variable_wind_info", "sys_maint_reqd"]].describe().T

                      count unique       top     freq
wban_number         6595372    903     14750    14690
call_sign           6595372    903      KGFL    14690
call_sign2          6595372    903       GFL    14690
year                6595372      1      2019  6595372
month               6595372      1        09  6595372
day                 6595372     29        03   268867
hour                6595372     25        00   296759
minute              6595372     13        00   549162
rec_length          6595372    251       109   709369
date                6595372     29  09/03/19   268858
timestamp           6595372    300  00:40:31    24745
interval            6595372      1     5-MIN  6595372
zulu_time           6595372   7587   250515Z      948
report_modifier     6595372    260      AUTO  3994336
wind_data           6595372      2      True  6507358
wind_direction      6595372     41       000  1249885
gusts               6595372      2     False  5931682
variable_winds      6595372      2     False  6226888
variable_wind_info  6595372    611            6533714
sys_maint_reqd      6595372      2     False  5803153

In [64]:
station_df.wban_number.count(), unique_station_df.wban_number.count(), noaa_df.wban_number.count(), merged_df.wban_number.count()

(29729, 26315, 6168769, 6595372)

In [49]:
# Write to file
parquet_file = "{}/noaa/Sep2019_withloc.parquet".format(datafolder)
write(parquet_file, merged_df,compression='GZIP')

In [55]:
# Filter out data for a single day 
Sep27_df = merged_df[merged_df.date == '09/27/19']

In [56]:
gusty = Sep27_df[Sep27_df['gusts'] == True]
print("There are",len(gusty),"records with gust data.")

There are 30949 records with gust data.

In [57]:
variable = Sep27_df[Sep27_df['variable_winds'] == True]
print("There are",len(variable),"records with variable wind data.")

There are 14925 records with variable wind data.

In [59]:
nowinddata = Sep27_df[Sep27_df['wind_data'] == False]
missing_wind = 0
for num in list(nowinddata.index):
#     print(lines[num])
    missing_wind += 1
print("There are",missing_wind,"records out of", len(lines), "without wind data.")

There are 3737 records out of 6168774 without wind data.

In [60]:
maintreqd = Sep27_df[Sep27_df['sys_maint_reqd'] == True]
print("There are {} records from systems requiring maintenance".format(len(maintreqd)))

There are 25154 records from systems requiring maintenance